# Generated by Django 4.2.5 on 2023-10-29 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Peso (Kg)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creacion')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesos', to='authuser.profile')),
            ],
            options={
                'verbose_name': 'Weight Record',
                'verbose_name_plural': 'Weight Records',
            },
        ),
    ]
