# Generated by Django 4.2.5 on 2023-10-17 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weightrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to=settings.AUTH_USER_MODEL),
        ),
    ]
