# Generated by Django 4.2.5 on 2023-10-29 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='Fecha de Creacion')),
                ('note', models.TextField(verbose_name='Nota')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_paciente', to='authuser.profile')),
            ],
            options={
                'verbose_name': 'Medical Note',
                'verbose_name_plural': 'Medical Notes',
            },
        ),
    ]
