# Generated by Django 4.2.5 on 2023-10-16 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0006_doctor_last_name_doctor_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='Fecha de Creacion')),
                ('note', models.TextField(verbose_name='Nota')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_doctor', to='authuser.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Note',
                'verbose_name_plural': 'Medical Notes',
            },
        ),
    ]
