# Generated by Django 4.2.5 on 2023-10-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_rename_name_profile_full_name'),
        ('medicalnote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalnote',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_paciente', to='authuser.profile', verbose_name='Paciente'),
        ),
    ]
