# Generated by Django 4.2.5 on 2023-11-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalnote', '0003_alter_medicalnote_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalnote',
            options={'ordering': ['id'], 'verbose_name': 'Medical Note', 'verbose_name_plural': 'Medical Notes'},
        ),
    ]
