# Generated by Django 4.2.5 on 2023-10-29 06:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('No', 'Normal'), ('El', 'Elevada'), ('H1', 'Hipertension Fase 1'), ('H2', 'Hipertension Fase 2')], max_length=2, null=True, verbose_name='Categoria')),
                ('sistolic', models.PositiveSmallIntegerField(verbose_name='Presion Arterial Sistolica (mmHg)')),
                ('diastolic', models.PositiveSmallIntegerField(verbose_name='Presion Arterial Diastolica (mmHg)')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Frecuencia Cardiaca (bpm)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creacion')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pressure_records', to='authuser.profile')),
            ],
            options={
                'verbose_name': 'Blood Pressure Record',
                'verbose_name_plural': 'Blood Pressure Records',
            },
        ),
    ]
