# Generated by Django 4.2.5 on 2023-10-13 04:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('No', 'Normal'), ('El', 'Elevada'), ('H1', 'Hipertension Fase 1'), ('H2', 'Hipertension Fase 2')], max_length=2, null=True, verbose_name='Categoria')),
                ('sistolic', models.PositiveSmallIntegerField(verbose_name='Presion Arterial Sistolica (mmHg)')),
                ('diastolic', models.PositiveSmallIntegerField(verbose_name='Presion Arterial Diastolica (mmHg)')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Frecuencia Cardiaca (bpm)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blood Pressure Record',
                'verbose_name_plural': 'Blood Pressure Records',
            },
        ),
    ]
