# Generated by Django 4.2.5 on 2023-11-03 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpressurerecord', '0002_alter_bloodpressurerecord_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressurerecord',
            name='diastolic',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(150)], verbose_name='Presion Arterial Diastolica (mmHg)'),
        ),
        migrations.AlterField(
            model_name='bloodpressurerecord',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)], verbose_name='Frecuencia Cardiaca (bpm)'),
        ),
        migrations.AlterField(
            model_name='bloodpressurerecord',
            name='sistolic',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)], verbose_name='Presion Arterial Sistolica (mmHg)'),
        ),
    ]
