# Generated by Django 4.2.5 on 2023-11-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpressurerecord', '0003_alter_bloodpressurerecord_diastolic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodpressurerecord',
            options={'ordering': ['id'], 'verbose_name': 'Blood Pressure Record', 'verbose_name_plural': 'Blood Pressure Records'},
        ),
    ]
