# Generated by Django 4.2.5 on 2023-10-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_user_birth_date_user_doctor_id_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Mujer'), ('H', 'Hombre'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Genero'),
        ),
    ]
