# Generated by Django 4.2.5 on 2023-11-05 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
