# Generated by Django 4.2.5 on 2023-10-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_doctor_alter_user_doctor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='especiality',
            new_name='speciality',
        ),
    ]
