# Generated by Django 4.2.5 on 2023-10-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_rename_especiality_doctor_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre'),
        ),
    ]
