# Generated by Django 4.2.5 on 2023-10-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0006_doctor_last_name_doctor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='doctor_id',
            new_name='doctor',
        ),
    ]
